[package]
name = "sand_simulation_v3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.9"
ggez = "0.9.3"
rand = "0.8.5"
strum = "0.25.0"
strum_macros = "0.25.3"
